config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :articles do
    resources :comments do
      member do
        get 'create_comment'
      end
    end
  end

  root 'articles#index'
  get 'signup', to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/articles_comment',  to: 'articles#comment'
  get '/articles_show_comments',  to: 'articles#show_comments'
  get '/create_comment_to_comment',  to: 'comment#create_comment'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  has_many :answer_comments, class_name: "Comment",
           foreign_key: "parent_comment_id",
           dependent: :destroy

  belongs_to :parent_comment, class_name: "Comment"
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  has_many :comments, dependent: :destroy

  attr_accessor :password

  attr_accessible :login, :avatar_link, :password, :password_confirmation

  validates :login, :presence => true,
            :length => { :maximum => 50 },
            :uniqueness => true

  validates :password, :presence => true,
            :confirmation => true,
            :length => { :within => 6..40 }

  before_save :encrypt_password, :default_values
  before_create :create_remember_token


  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(login, submitted_password)
    user = find_by_login(login)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt_token(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def default_values
      if new_record?
        if self.avatar_link == ''
          avatar_link_adr = 'http://claimmyrun.com/static/img/default-avatar-160.png'
          self.avatar_link = avatar_link_adr
        end
      end
    end

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password) if new_record?
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
      #secure_hash(string)
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

    def create_remember_token
      self.remember_token = User.encrypt_token(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :funk, only: [:comment, :destroy]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
  end

  def comment

  end

  def show_comments
    @article = Article.find(params[:article_id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

    def funk
      @article = Article.find(params[:id])
      respond_to do |format|
        format.js
        format.html
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :funk, only: [:create_comment, :destroy]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def destroy
    @comment.destroy
  end


  def create_comment
  end

  private
    def comment_params
      params.require(:comment).permit(:body,:user_id ,:parent_comment_id)
    end

    def funk
      @article = Article.find(params[:article_id])
      @comment = Comment.find(params[:id])
      respond_to do |format|
        format.js
        format.html
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if signed_in?
      redirect_to current_user
    end
  end

  def create
    user = User.find_by(login: params[:session][:login])

    if user && User.authenticate(params[:session][:login],
                                 params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid login/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @title = @user.login
  end

  private
  def user_params
    params.require(:user).permit(:login, :avatar_link,
                                 :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt_token(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt_token(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt_token(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_by_id(id)
    User.find_by_id(id)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, :required => 'required'%>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, :required => 'required' %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/comment.js.erb
$(document.getElementById('new_comment')).remove();
$(document.getElementById('article')).append('<%= j render "comments/form" %>');

app/views/articles/destroy.js.erb
document.getElementById("<%= @article.id %>").remove();

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<% if signed_in? %>
  <%= link_to 'New article', new_article_path %>
<% end %>
<% @articles.each do |article| %>
    <div id=<%= article.id %>>
      <div class="article_header">
        <%= image_tag (user_by_id(article.user_id).avatar_link), width: 20, height: 20 %>
        <%= user_by_id(article.user_id).login %>
        <%= link_to article.title, article_path(article) , class: "article_title"%>
        <% if current_user && article.user_id == current_user.id %>
          <%= link_to 'Edit', edit_article_path(article)%>
          <%= link_to 'Destroy', article_path(article),
                           method: :delete,
                           id: article.id,
                           data: { confirm: 'Are you sure?',
                                   :remote => true}%>
        <% end %>

      </div>
      <p class="article_content"><%= article.text %></p>
    </div>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div id = 'article'>
  <p>
    <strong>Author:</strong>
    <%= User.find_by_id(@article.user_id).login %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>
  <% if current_user && @article.user_id == current_user.id %>
    <%= link_to 'Edit', edit_article_path(@article) %>
  <%end%>
  <% if current_user %>
    <%= link_to 'Comment',
                :action => "comment",
                :id => @article.id,
                :remote => true %>
  <%end%>
  <span id='show_comments_link'>
    <%= link_to 'Show comments',
                :action => "show_comments",
                :article_id => @article.id,
                :remote => true %>
  </span>

</div>
<div id="comments">
</div>

app/views/articles/show_comments.js.erb
show_comments($(document.getElementById("comments")));

function show_comments(elem)
{
  document.getElementById('show_comments_link').remove();

  elem.append('<h2 id = "comments_title">Comments</h2>');
  elem.append('<%=j render @article.comments%>');

  var comments = document.getElementsByClassName('comment');
  build_tree(comments);
}

app/views/comments/_comment.html.erb
<div id=<%=comment.id%>_parent-<%=comment.parent_comment_id%> class="comment">
  <div class="comment_header">
    <%= image_tag (user_by_id(comment.user_id).avatar_link), width: 20, height: 20 %>
    <span><%= user_by_id(comment.user_id).login %></span>
    <span class="comments_links">
      <% if current_user %>
        <%= link_to 'Comment', [:create_comment, comment.article, comment], :remote => true %>
      <%end%>
      <% if current_user && comment.user_id == current_user.id %>
        <%= link_to 'Destroy Comment', [comment.article, comment],
                    method: :delete, :remote =>true,
                    data: { confirm: 'Are you sure?' } %>
      <%end%>
    </span>
  </div>
  <div id="comment_content">
    <%= comment.body %>
  </div>
  <div clas="answer_place"></div>
</div>

app/views/comments/_form.html.erb
<div id="new_comment">
  <%= form_for([@article, @article.comments.build], :remote => true ) do |f| %>
      <p>
        <%= f.label :body %><br>
        <%= f.text_area :body, :required => 'required'%>
        <%= f.hidden_field :parent_comment_id,
                           :value => params[:controller] == 'comments' ? params[:id] : nil %>
        <%= f.hidden_field :user_id,
                           :value => current_user.id %>
      </p>
      <p>
        <%= f.submit %>
      </p>
  <% end %>
</div>

app/views/comments/create.js.erb
$(document.getElementById('new_comment')).remove();
show_comments($(document.getElementById("comments")));

function show_comments(elem)
{
  if(document.getElementById("comments_title"))
  {
    if('<%=@comment.parent_comment_id%>' > 0)
    {
      add_comments(elem);
    }
    else
    {
      $(document.getElementById('no_comments_info')).remove();
      elem.append('<%=j render @comment%>');
    }
  }
  else
  {
    document.getElementById('show_comments_link').remove();
    add_comments(elem);
  }
}

function add_comments(elem)
{
  elem.html('');
  elem.append('<h2 id = "comments_title">Comments</h2>');
  elem.append('<%=j render @article.comments%>');
  var comments = document.getElementsByClassName('comment');
  build_tree(comments);
}

app/views/comments/create_comment.js.erb
$(document.getElementById('new_comment')).remove();
show_comment_form();

function show_comment_form()
{
  var comment_id ='<%=@comment.id%>_parent-<%=@comment.parent_comment_id%>';
  var comment = document.getElementById(comment_id);
  var field_place = comment.getElementsByTagName('div')[2];
  $(field_place).append('<%= j render "form" %>');
}

app/views/comments/destroy.js.erb
$(document.getElementById("<%=@comment.id%>_parent-<%=@comment.parent_comment_id%>")).remove();

app/views/layouts/_top.html.erb
<div class="top">
  <%= link_to "Home", root_path %>
  <% if signed_in? %>
      <%= link_to @current_user.login, current_user %>
      <%= link_to "Sign out", signout_path, method: "delete" %>

  <% else %>
      <%= link_to "Sign in", signin_path %>
      <%= link_to "Sign up", signup_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/top' %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<table>

  <% if @users.nil? %>
      <tr>
        <td>No users</td>
      </tr>
  <% else %>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.login %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
          </tr>
      <% end %>
  <% end %>

</table>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for :user, url: {action: "create"} do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            There is some errors:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :Login %><br>
      <%= f.text_field :login %>
    </p>

    <p>
      <%= f.label :"Avatar link" %><br>
      <%= f.text_field :avatar_link %>
    </p>

    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.label :"Check password" %><br>
      <%= f.password_field :password_confirmation %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/users/show.html.erb
User: <%= @user.login %><br>
<%= image_tag @user.avatar_link, width: 150, height: 150%>